package hmof

import org.hibernate.envers.Audited

@Audited
class CommerceObject {
	static searchable = true
	String objectName
	String isbnNumber
	
	
	Date dateCreated
	Date lastUpdated	
	
	String pathToCoverImage
	String teacherLabel
	String teacherUrl
	String studentLabel
	String studentUrl
	String objectType
	Integer objectReorderNumber = 1
	String gradeLevel
	String comments = ("Autogenerated: " + new Date().format('dd/MM/yy'))
	
	ContentType contentType
			
	static belongsTo = SecureProgram

	static constraints = {

		objectName (blank: false, unique: true)
		isbnNumber (blank: false, unique: true)
		
		dateCreated ()
		lastUpdated ()	
		
		pathToCoverImage (blank: false, nullable:true)
		teacherLabel (blank: false, nullable:true)
		teacherUrl (blank: false, nullable:true)
		studentLabel (blank: false, nullable:true)
		studentUrl (blank: false, nullable:true)
		objectType (inList: ['DLO', 'eBook','myWriteSmart Activities', 'FYI', 'IWB', 'Notebook', 'Professional Development', 'Tab', 'Other'], nullable:true)
		objectReorderNumber ( validator: {return it > 0 &&  (String.valueOf(it).length()) < 3 }, blank: false, nullable:true)
		gradeLevel (inList: ['6' ,'7' , '8', '9', '10', '11', '12', '6-8', '9-12', '6-12' ] , nullable:true)
		comments (maxSize:200, nullable:true, widget: 'textarea')
	}

	String toString(){
		"${objectName}"
	}
}
