package hmof

class CommerceObject {

	String objectName
	String isbn
	String pathToCoverImage
	String teacherLabel
	String teacherUrl
	String studentLabel
	String studentUrl
	String objectType
	Integer objectReorderNumber = 1
	Integer gradeLevel
	String comments = ("Autogenerated: " + new Date().format('dd/MM/yy'))
	Date dateCreated
	Date lastUpdated 
		
	static belongsTo = Bundle

	static constraints = {

		objectName (blank: false, unique: true)
		isbn (blank: false, unique: true)
		pathToCoverImage (blank: false, nullable:true)
		teacherLabel (blank: false, nullable:true)
		teacherUrl (blank: false, nullable:true)
		studentLabel (blank: false, nullable:true)
		studentUrl (blank: false, nullable:true)
		objectType (inList: ['DLO', 'eBook','myWriteSmart Activities', 'FYI', 'IWB', 'Notebook', 'Professional Development', 'Tab', 'Other'], nullable:true)
		objectReorderNumber ( validator: {return it > 0 &&  (String.valueOf(it).length()) < 3 }, blank: false, nullable:true)
		gradeLevel (inList: [6 ,7 , 8, 9, 10, 11, 12] , nullable:true)
		comments (maxSize:200, nullable:true, widget: 'textarea')
	}

	String toString(){
		"${objectName}"
	}
}
