package hmof

class SecureProgram {

	String productName
	String registrationIsbn
	String onlineIsbn
	Integer copyright
	String labelLink
	String pathToResource
	String pathToCoverImage
	Boolean knewtonProduct

	String securityWord = "changeme"
	String securityWordLocation = "1"
	String securityWordPage = "5"

	Boolean includeDashboardObject
	Boolean includeEplannerObject

	String comments = ("Autogenerated: " + new Date().format('dd/MM/yy'))

	static belongsTo = Bundle
	//static belongsTo = [bundle:Bundle]
	//static hasMany = [commerceObjects:Cobj, bundles:Bundle]
	//static hasMany = [commerceObjects:Cobj]
	
	Date dateCreated
	Date lastUpdated  

	static constraints = {

		productName (blank: false)
		registrationIsbn (blank: false, unique: true)
		onlineIsbn (blank: false)
		copyright (blank: false, nullable:true)
		labelLink (blank: false, nullable:true)
		pathToResource (blank: false, nullable:true)
		pathToCoverImage (blank: false, nullable:true)
		knewtonProduct (nullable:true)
		securityWord (blank: false)
		securityWordLocation (blank: false)
		securityWordPage (blank: false)
		includeDashboardObject (nullable:true)
		includeEplannerObject (nullable:true)
		comments (maxSize:255, nullable:true, widget: 'textarea')
	}

	String toString(){
		"${productName}"
	}
}
