package hmof

import java.util.Date
import org.hibernate.envers.Audited

@Audited
class SecureProgram {
	//static searchable = true
	String productName
	String registrationIsbn
	String onlineIsbn
	String copyright
	String labelForOnlineResource
	String pathToResource
	String pathToCoverImage

	Date dateCreated
	Date lastUpdated

	String labelForTeacherAdditionalResource
	String pathToTeacherAdditionalResource
	String labelForStudentAdditionalResource
	String pathToStudentAdditionalResource

	String securityWord = "changeme"
	String securityWordLocation = "1"
	String securityWordPage = "5"

	Boolean includeDashboardObject
	Boolean includeEplannerObject

	Boolean knewtonProduct
	String knowledgeGraphIdDev
	String knowledgeGraphIdQA
	String knowledgeGraphIdProd
	Integer knowledgeGraphWarmUpTimeLimit
	Integer knowledgeGraphEnrichmentTimeLimit
	Integer knowledgeGraphEnrichmentCbiTimeLimit

	String comments = ("Autogenerated: " + new Date().format('dd/MM/yy'))

	ContentType contentType

	static belongsTo = Bundle
	static hasMany = [commerceObjects:CommerceObject]
	static searchable = { commerceObjects component: true }
	static constraints = {

		productName (blank:false,nullable:false)
           
		registrationIsbn (blank: false,nullable:false, unique: true)
		onlineIsbn (blank: false,nullable:false)

		dateCreated ()
		lastUpdated ()

		copyright (blank: false, nullable:true)
		labelForOnlineResource (blank: false, nullable:true)
		pathToResource (blank: false, nullable:true)
		pathToCoverImage (blank: false, nullable:true)

		labelForTeacherAdditionalResource (nullable:true)
		pathToTeacherAdditionalResource (nullable:true)
		labelForStudentAdditionalResource (nullable:true)
		pathToStudentAdditionalResource (nullable:true)

		securityWord (blank: false)
		securityWordLocation (blank: false)
		securityWordPage (blank: false)
		includeDashboardObject (nullable:true)
		includeEplannerObject (nullable:true)

		knewtonProduct (nullable:true)
		knowledgeGraphIdDev (nullable:true,validator: { val, obj ->
			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{

				if(null==val){

					return 'hmof.SecureProgram.knowledgeGraphIdDev.matches.invalid'
				}else{

					return true
				}
			}else
			{
				return true
			}
		},blank:false,matches: /([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$/)
		knowledgeGraphIdQA (nullable:true,validator: { val, obj ->

			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{
				
				if(null==val){
					
					return 'hmof.SecureProgram.knowledgeGraphIdQA.matches.invalid'
				}else{

					return true
				}
			}else
			{
				return true
			}
		},blank:false,matches: /([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$/)
		knowledgeGraphIdProd (nullable:true,validator: { val, obj ->

			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{				
				if(null==val){					
					return 'hmof.SecureProgram.knowledgeGraphIdProd.matches.invalid'
				}else{
					return true
				}
			}else
			{
				return true
			}
		},blank:false,matches: /([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$/)
		knowledgeGraphWarmUpTimeLimit (nullable:true,validator: { val, obj ->

			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{				
				if(null==val){					
					return 'SecureProgram.knowledgeGraphWarmUpTimeLimit.range'
				}else{
					return true
				}
			}else
			{
				return true
			}
		},blank:false,range:5..60)
		knowledgeGraphEnrichmentTimeLimit (nullable:true,validator: { val, obj ->

			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{			
				if(null==val){					
					return 'SecureProgram.knowledgeGraphEnrichmentTimeLimit.range'
				}else{

					return true
				}
			}else
			{
				return true
			}
		},blank:false,range:5..60)
		knowledgeGraphEnrichmentCbiTimeLimit (nullable:true,validator: { val, obj ->

			if(obj.knewtonProduct!=null && obj.knewtonProduct)
			{
				if(null==val){
					return 'SecureProgram.knowledgeGraphEnrichmentCbiTimeLimit.range'
				}else{
					return true
				}
			}else
			{
				return true
			}
		},blank:false,range:5..60)

		comments (maxSize:255, nullable:true, widget: 'textarea')
	}

	String toString(){
		"${productName}"
	}
}
